import { Comfortaa } from "next/font/google";
import "./globals.css";

const comf = Comfortaa({
  variable: "--font-comfortaa",
  subsets: ["latin"],
});

export const metadata = {
  title: "DUMARK Vakf",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${comf.variable}`}>
        {children}
      </body>
    </html>
  );
}
